### ISSUE TITLE
RedHat packaging

### ISSUE THREAD

**Issue by vvidic** [perfsonar/pstracetree#2]
Prepare RPM packages for installing on CentOS 7.

**Comment by vvidic** [comment]
Some questions before packaging:

1. package name to use
2. location for installing in the OS
3. URL prefix to use for this application

**Comment by tonin** [comment]
I would suggest:

1. perfsonar-tracetree
1. `/usr/lib/perfsonar/tracetree/`
1. `/perfsonar-tracetree/`

@okvittem and @arlake228 comments?

**Comment by vvidic** [comment]
On Wed, Nov 28, 2018 at 07:49:24AM -0800, Antoine Delvaux wrote:
> I would suggest:
> 
> 1. perfsonar-tracetree
> 1. `/usr/lib/perfsonar/tracetree/`
> 1. `/perfsonar-tracetree/`

Ok, and we also need a version: 1.0 or 0.1 or something else?

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNET
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by mfeit-internet2** [comment]
Comments:

I would recommend `/usr/libexec` over `/usr/lib` if the primary contents are executabless.

For the URL, maybe adopt the pScheduler convention and make it `/tracetree`.  Adding `perfsonar` to it seems redundant redundant.

**Comment by vvidic** [comment]
Initial packages available in nightly.
