### ISSUE TITLE
Make pstracetree dependant on the graphs package and use same JS libraries

### ISSUE THREAD

**Issue by laeti-tia** [perfsonar/pstracetree#4]
The pstracetree component is meant to be part of the toolkit and MaDDash visualisation UI.  This means it will most probably always get installed with the [graphs package](https://github.com/perfsonar/graphs).

It would then make sense to use the same JS libraries and versions in both packages so that we reduce the number of files shipped in packages and loaded by the browser.  I'm mostly thinking about JQuery and the way CORS requests are handled, but maybe there are others too.

An alternative might be to merge pstracetree within the graphs package/repository.

**Comment by arlake228** [comment]
Need for final but not necessarily for beta

**Comment by ottojwittner** [comment]
Javascript libs required for displaying graphics are built along side the pstracetree package.
