### ISSUE TITLE
Provide an optional pstracetree package for user to try

### ISSUE THREAD

**Issue by laeti-tia** [perfsonar/pstracetree#5]
We will not release the pstracetree with 4.2 but it would be good to provide a first package that users can optionally install to try out.  And then [document the package installation and usage](https://github.com/perfsonar/docs/issues/180) in the wiki.

We need:
- automatic build of pstracetree RPM
- automatic build of pstracetree Deb

**Comment by ottojwittner** [comment]
This issue is now relevant in relation to getting the Microdep analytics and map view packaged as it depends on pstracetree.
